COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.0 
   **************************************************

   This file holds the implementation in NEURON of the Cell Mechanism:
   LeakConductance (Type: Channel mechanism, Model: Template based ChannelML file)

   with parameters: 
   /channelml/@units = Physiological Units 
   /channelml/notes = ChannelML file containing a single Channel description 
   /channelml/channel_type/@name = LeakConductance 
   /channelml/channel_type/@density = yes 
   /channelml/channel_type/status/@value = in_progress 
   /channelml/channel_type/status/contributor/name = Padraig Gleeson 
   /channelml/channel_type/status/contributor/comment =  Note: This is not (yet) based on experimental data from C. elegans 
   /channelml/channel_type/notes = Simple example of a leak/passive conductance. 
   /channelml/channel_type/current_voltage_relation/@cond_law = ohmic 
   /channelml/channel_type/current_voltage_relation/@ion = non_specific 
   /channelml/channel_type/current_voltage_relation/@default_erev = -65 
   /channelml/channel_type/current_voltage_relation/@default_gmax = 0.25 

// File from which this was generated: C:\Users\Tom\Documents\research\OpenWorm\CElegansNeuroConstruct\CElegansNeuroML\CElegans\cellMechanisms\LeakConductance\LeakConductance.xml

// XSL file with mapping to simulator: C:\Users\Tom\Documents\research\OpenWorm\CElegansNeuroConstruct\CElegansNeuroML\CElegans\cellMechanisms\LeakConductance\ChannelML_v1.8.1_NEURONmod.xsl

ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file containing a single Channel description
ENDCOMMENT

TITLE Channel: LeakConductance

COMMENT
    Simple example of a leak/passive conductance.
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX LeakConductance
    ? A non specific current is present
    RANGE e
    NONSPECIFIC_CURRENT i
    
    RANGE gmax, gion
    
}

PARAMETER { 
      

    gmax = 0.00025 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    e = -65 (mV) ? default value, should be overwritten when conductance placed on cell
    
}



ASSIGNED {
      

    v (mV)
        
    i (mA/cm2)
        
}

BREAKPOINT { 
    i = gmax*(v - e) 
        

}


