#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/users/6/portegys/nrn-7.3"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/users/6/portegys/nrn-7.3/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/usr/users/6/portegys/bionet/sim/model/x86_64/.libs/libnrnmech.so" "$@"
